/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import java.awt.Font;
import java.awt.print.PrinterException;
import static java.lang.Float.sum;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Mart extends javax.swing.JFrame {
    float sum;

    /**
     * Creates new form Mart
     */
    private DefaultTableModel model;
    public Mart() {
        initComponents();
        String col[]={"Code","Name","Qty","Price","Total"};
        model = new DefaultTableModel();
        model.setColumnIdentifiers(col);
        ttable.setModel(model);
    }
    void clear(){
        txcode.setText("");
        txname.setText("");
        txqty.setText("");
        txprice.setText("");
    }
    public void GetData(){
        for(int i=0;i<Market.mark.size();i++){
            Object obj[]={
                Market.mark.get(i).code,
                Market.mark.get(i).name,
                Market.mark.get(i).qty,
                Market.mark.get(i).price,
                Market.mark.get(i).total,
            };
            model.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txqty = new javax.swing.JTextField();
        txprice = new javax.swing.JTextField();
        txcode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtsum = new javax.swing.JTextField();
        bt6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Market");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 10, 70, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 190, 40, 16);
        jPanel1.add(txname);
        txname.setBounds(100, 100, 160, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Code");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 70, 40, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("QTY");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 150, 40, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 110, 40, 16);
        jPanel1.add(txqty);
        txqty.setBounds(100, 140, 160, 30);
        jPanel1.add(txprice);
        txprice.setBounds(100, 180, 160, 30);
        jPanel1.add(txcode);
        txcode.setBounds(100, 60, 160, 30);

        ttable.setBackground(new java.awt.Color(0, 0, 0));
        ttable.setForeground(new java.awt.Color(225, 225, 225));
        ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ttable.setGridColor(new java.awt.Color(225, 225, 225));
        ttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 50, 350, 160);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 280, 72, 22);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 280, 72, 22);

        jButton3.setForeground(new java.awt.Color(225, 0, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 280, 72, 22);

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 280, 72, 22);

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(380, 280, 72, 22);

        txtsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsumActionPerformed(evt);
            }
        });
        jPanel1.add(txtsum);
        txtsum.setBounds(180, 220, 80, 30);

        bt6.setForeground(new java.awt.Color(0, 0, 225));
        bt6.setText("Total");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt6);
        bt6.setBounds(100, 230, 60, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/11.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 650, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void sum(){
        for(int i=0;i<ttable.getRowCount();i++){
            sum =sum +Float.parseFloat(ttable.getValueAt(i, 4).toString());
        }
        txtsum.setText(Float.toString(sum));
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        model.setRowCount(0);
        Market.mark.add(new Market(txcode.getText(),txname.getText(),
        Float.parseFloat(txqty.getText()),
        Float.parseFloat(txprice.getText()),
        Float.parseFloat(txqty.getText())*Float.parseFloat(txprice.getText())));
        
        
        clear();
        GetData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index = ttable.getSelectedRow();
        model.setRowCount(0);
        Market.mark.add(index,new Market(txcode.getText(),txname.getText(),
        Float.parseFloat(txqty.getText()),
        Float.parseFloat(txprice.getText()),
        Float.parseFloat(txqty.getText())*Float.parseFloat(txprice.getText())));
        
        GetData();
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = ttable.getSelectedRow();
        model.removeRow(row);
        Market.mark.remove(row);
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttableMouseClicked
        // TODO add your handling code here:
        int row = ttable.getSelectedRow();
        txcode.setText(model.getValueAt(row, 0).toString());
        txname.setText(model.getValueAt(row, 1).toString());
        txqty.setText(model.getValueAt(row, 2).toString());
        txprice.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_ttableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MessageFormat header = new MessageFormat("Item Report.");
        try{
            this.ttable.print(JTable.PrintMode.NORMAL,header,null);
        } catch (PrinterException ex) {
            Logger.getLogger(Mart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsumActionPerformed
        
    }//GEN-LAST:event_txtsumActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        bt6.setFont(new Font("Serif",Font.PLAIN,14));
        sum();
    }//GEN-LAST:event_bt6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ttable;
    private javax.swing.JTextField txcode;
    private javax.swing.JTextField txname;
    private javax.swing.JTextField txprice;
    private javax.swing.JTextField txqty;
    private javax.swing.JTextField txtsum;
    // End of variables declaration//GEN-END:variables
}
